//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VastGIS.Plugins.Printing.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VastGIS.Plugins.Printing.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string AppManager_Home {
            get {
                return ResourceManager.GetString("AppManager_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive File 的本地化字符串。
        /// </summary>
        internal static string ArchiveFile {
            get {
                return ResourceManager.GetString("ArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument %S cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeNegative_S {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNegative_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument %S1 could not be successfully cast into %S2. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCouldNotBeCast_S1_S2 {
            get {
                return ResourceManager.GetString("ArgumentCouldNotBeCast_S1_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument %S was null.  Try testing for the null case before calling this method. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_S {
            get {
                return ResourceManager.GetString("ArgumentNull_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument %S1 was incorrect for %S2. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOfWrongType_S1_S2 {
            get {
                return ResourceManager.GetString("ArgumentOfWrongType_S1_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument %S was outside the range of accepted values. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRangeException_S {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file type was supposedly bgd, but there was a problem with reading the data type. 的本地化字符串。
        /// </summary>
        internal static string bgdDataTypeError {
            get {
                return ResourceManager.GetString("bgdDataTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary rasters only support one band, which is the raster itself. 的本地化字符串。
        /// </summary>
        internal static string BinarySupportsOneBand {
            get {
                return ResourceManager.GetString("BinarySupportsOneBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument byteArray was too small to contain the requested information 的本地化字符串。
        /// </summary>
        internal static string ByteArrayTooSmall {
            get {
                return ResourceManager.GetString("ByteArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculating Statistics 的本地化字符串。
        /// </summary>
        internal static string CalculatingStatistics {
            get {
                return ResourceManager.GetString("CalculatingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fileName %S cannot be copied to itself. 的本地化字符串。
        /// </summary>
        internal static string CannotCopyToSelf_S {
            get {
                return ResourceManager.GetString("CannotCopyToSelf_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        internal static string cat_behavior {
            get {
                return ResourceManager.GetString("cat_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string cat_layout {
            get {
                return ResourceManager.GetString("cat_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        internal static string cat_map {
            get {
                return ResourceManager.GetString("cat_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        internal static string cat_scale {
            get {
                return ResourceManager.GetString("cat_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string cat_size {
            get {
                return ResourceManager.GetString("cat_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol 的本地化字符串。
        /// </summary>
        internal static string cat_symbol {
            get {
                return ResourceManager.GetString("cat_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Properties 的本地化字符串。
        /// </summary>
        internal static string cat_template {
            get {
                return ResourceManager.GetString("cat_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the text you want to display in the legend. 的本地化字符串。
        /// </summary>
        internal static string ColorBreakCaptionHelp {
            get {
                return ResourceManager.GetString("ColorBreakCaptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left click after selecting to edit, or right click to assign a color range. 的本地化字符串。
        /// </summary>
        internal static string ColorBreakColorHelp {
            get {
                return ResourceManager.GetString("ColorBreakColorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raster values should be numeric and be drawn with a range like [low] - [high] 的本地化字符串。
        /// </summary>
        internal static string ColorBreakNotNumeric {
            get {
                return ResourceManager.GetString("ColorBreakNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value or range of values shown as [low] - [high] 的本地化字符串。
        /// </summary>
        internal static string ColorBreakValue {
            get {
                return ResourceManager.GetString("ColorBreakValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of ordinates did not match between the dimensions, so the hyperdistance cannot be accurately calculated. 的本地化字符串。
        /// </summary>
        internal static string CoordinateMismatchException {
            get {
                return ResourceManager.GetString("CoordinateMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copying Values 的本地化字符串。
        /// </summary>
        internal static string CopyingValues {
            get {
                return ResourceManager.GetString("CopyingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copying values from %S1 to %S2 的本地化字符串。
        /// </summary>
        internal static string CopyingValues_S1_S2 {
            get {
                return ResourceManager.GetString("CopyingValues_S1_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copying Values from %S 的本地化字符串。
        /// </summary>
        internal static string CopyingValuesFrom_S {
            get {
                return ResourceManager.GetString("CopyingValuesFrom_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copying Values from %S1 to %S2 的本地化字符串。
        /// </summary>
        internal static string CopyingValuesFrom_S1_To_S2 {
            get {
                return ResourceManager.GetString("CopyingValuesFrom_S1_To_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not execute the query. 的本地化字符串。
        /// </summary>
        internal static string CouldNotExecuteQuery {
            get {
                return ResourceManager.GetString("CouldNotExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find or replace items. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindReplace {
            get {
                return ResourceManager.GetString("CouldNotFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating Shaded Relief 的本地化字符串。
        /// </summary>
        internal static string CreatingShadedRelief {
            get {
                return ResourceManager.GetString("CreatingShadedRelief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating Texture 的本地化字符串。
        /// </summary>
        internal static string CreatingTexture {
            get {
                return ResourceManager.GetString("CreatingTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current element was not defined.  Before attempting to read the element, first assign the value of the current XML Element to read. 的本地化字符串。
        /// </summary>
        internal static string CurrentElementNotSpecified {
            get {
                return ResourceManager.GetString("CurrentElementNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In order to specify a custom filter expression, the custom mode must be selected first. 的本地化字符串。
        /// </summary>
        internal static string CustomOnly {
            get {
                return ResourceManager.GetString("CustomOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Extensions 的本地化字符串。
        /// </summary>
        internal static string DataExtensions {
            get {
                return ResourceManager.GetString("DataExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter %S was not the correct datatype. 的本地化字符串。
        /// </summary>
        internal static string DataTypeIncorrect_S {
            get {
                return ResourceManager.GetString("DataTypeIncorrect_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Number of digits to show after the decimal. 的本地化字符串。
        /// </summary>
        internal static string DecimalCount {
            get {
                return ResourceManager.GetString("DecimalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This should be an integer from 0 to 15. 的本地化字符串。
        /// </summary>
        internal static string DecimalCountInvalid {
            get {
                return ResourceManager.GetString("DecimalCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no setting for the default Tool Provider. It scans the same folders the ToolManager scans for Tool Providers 的本地化字符串。
        /// </summary>
        internal static string DefaultToolproviderSettingsDialogText {
            get {
                return ResourceManager.GetString("DefaultToolproviderSettingsDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Tool Provider Settings 的本地化字符串。
        /// </summary>
        internal static string DefaultToolproviderSettingsDialogTitle {
            get {
                return ResourceManager.GetString("DefaultToolproviderSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value entered could not be correctly parsed into a valid double precision floating point value. 的本地化字符串。
        /// </summary>
        internal static string DoubleError {
            get {
                return ResourceManager.GetString("DoubleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a double precision floating point value. 的本地化字符串。
        /// </summary>
        internal static string DoubleHelp {
            get {
                return ResourceManager.GetString("DoubleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read past the end of the file. 的本地化字符串。
        /// </summary>
        internal static string EndOfFile {
            get {
                return ResourceManager.GetString("EndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Find String 的本地化字符串。
        /// </summary>
        internal static string EnterFindString {
            get {
                return ResourceManager.GetString("EnterFindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while while activating {0}. 的本地化字符串。
        /// </summary>
        internal static string ErrorWhileWhileActivating {
            get {
                return ResourceManager.GetString("ErrorWhileWhileActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression 的本地化字符串。
        /// </summary>
        internal static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extensions 的本地化字符串。
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Factorial value should be grater than 0 的本地化字符串。
        /// </summary>
        internal static string FactGreaterThanZero {
            get {
                return ResourceManager.GetString("FactGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Features 的本地化字符串。
        /// </summary>
        internal static string FeaturesAll {
            get {
                return ResourceManager.GetString("FeaturesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The feature set is invalid. 的本地化字符串。
        /// </summary>
        internal static string FeaturesetInvalid {
            get {
                return ResourceManager.GetString("FeaturesetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No feature set is specified. 的本地化字符串。
        /// </summary>
        internal static string FeaturesetMissing {
            get {
                return ResourceManager.GetString("FeaturesetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The feature set is valid. 的本地化字符串。
        /// </summary>
        internal static string FeaturesetValid {
            get {
                return ResourceManager.GetString("FeaturesetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Features in View Extent 的本地化字符串。
        /// </summary>
        internal static string FeaturesExtent {
            get {
                return ResourceManager.GetString("FeaturesExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected features 的本地化字符串。
        /// </summary>
        internal static string FeaturesSelected {
            get {
                return ResourceManager.GetString("FeaturesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The feature type cannot be changed here.  Try creating a new feature of the appropriate type. 的本地化字符串。
        /// </summary>
        internal static string FeatureTypeCannotChange {
            get {
                return ResourceManager.GetString("FeatureTypeCannotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The feature set selected was the incorrect type. 的本地化字符串。
        /// </summary>
        internal static string FeatureTypeException {
            get {
                return ResourceManager.GetString("FeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FeatureType of the feature you are trying to add does not match the feature type of this featureset. 的本地化字符串。
        /// </summary>
        internal static string FeatureTypeMismatch {
            get {
                return ResourceManager.GetString("FeatureTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FeatureType specified was not the line feature type. 的本地化字符串。
        /// </summary>
        internal static string FeatureTypeNotLine {
            get {
                return ResourceManager.GetString("FeatureTypeNotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FeatureType specified was not the point feature type.  的本地化字符串。
        /// </summary>
        internal static string FeatureTypeNotPoint {
            get {
                return ResourceManager.GetString("FeatureTypeNotPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FeatureType specified was not the polygon feature type. 的本地化字符串。
        /// </summary>
        internal static string FeatureTypeNotPolygon {
            get {
                return ResourceManager.GetString("FeatureTypeNotPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FeatureType was not specified.  Please specify a featuretype before attempting to call this method. 的本地化字符串。
        /// </summary>
        internal static string FeaturetypeUnspecified {
            get {
                return ResourceManager.GetString("FeaturetypeUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not import column fields. 的本地化字符串。
        /// </summary>
        internal static string FieldImportFailed {
            get {
                return ResourceManager.GetString("FieldImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified field is not a numeric field and so the &quot;EqualBreaks&quot; option is not supported. 的本地化字符串。
        /// </summary>
        internal static string FieldNotNumeric {
            get {
                return ResourceManager.GetString("FieldNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fileName %S already exists.  Do you wish to overwrite it? 的本地化字符串。
        /// </summary>
        internal static string FileExists_S {
            get {
                return ResourceManager.GetString("FileExists_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fileName %S was not found. 的本地化字符串。
        /// </summary>
        internal static string FileNotFound_S {
            get {
                return ResourceManager.GetString("FileNotFound_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fileName %S contains a feature type other than lines. 的本地化字符串。
        /// </summary>
        internal static string FileNotLines_S {
            get {
                return ResourceManager.GetString("FileNotLines_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fileName %S contains a feature type other than points. 的本地化字符串。
        /// </summary>
        internal static string FileNotPoints_S {
            get {
                return ResourceManager.GetString("FileNotPoints_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file was too large to fit into memory all at once.  Try using a DataSource instead. 的本地化字符串。
        /// </summary>
        internal static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified file type is not supported. 的本地化字符串。
        /// </summary>
        internal static string FileTypeNotSupported {
            get {
                return ResourceManager.GetString("FileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Tool 的本地化字符串。
        /// </summary>
        internal static string FindToolByName {
            get {
                return ResourceManager.GetString("FindToolByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property or method is overrided in a subclass and should not be used directly. 的本地化字符串。
        /// </summary>
        internal static string ImplementedInSubclass {
            get {
                return ResourceManager.GetString("ImplementedInSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The destination field data type is incompatible (double or string or integer) 的本地化字符串。
        /// </summary>
        internal static string IncompatibleDestinationField {
            get {
                return ResourceManager.GetString("IncompatibleDestinationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error while attempting to index %S 的本地化字符串。
        /// </summary>
        internal static string IndexingErrorIn_S {
            get {
                return ResourceManager.GetString("IndexingErrorIn_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input 的本地化字符串。
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of dimensions in %S is insufficient for this calculation. 的本地化字符串。
        /// </summary>
        internal static string InsufficientDimensions_S {
            get {
                return ResourceManager.GetString("InsufficientDimensions_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value is invalid, it must be a decimal between %min and %max 的本地化字符串。
        /// </summary>
        internal static string InvalidDouble {
            get {
                return ResourceManager.GetString("InvalidDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value is invalid, it must be an integer between %min and %max 的本地化字符串。
        /// </summary>
        internal static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value entered was not understood.  Please use either numbers or syntax &apos;start - end&apos;, e.g. &apos;1-5&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidNumberFormat {
            get {
                return ResourceManager.GetString("InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified key already exists in the tree. 的本地化字符串。
        /// </summary>
        internal static string KeyDuplicateException {
            get {
                return ResourceManager.GetString("KeyDuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified key could not be found in the tree. 的本地化字符串。
        /// </summary>
        internal static string KeyMissingException {
            get {
                return ResourceManager.GetString("KeyMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The size of the key did not match the size of the tree. 的本地化字符串。
        /// </summary>
        internal static string KeySizeException {
            get {
                return ResourceManager.GetString("KeySizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Bottom 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuBottom {
            get {
                return ResourceManager.GetString("LayoutCmnuBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to Height 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuHeight {
            get {
                return ResourceManager.GetString("LayoutCmnuHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Horizontal 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuHor {
            get {
                return ResourceManager.GetString("LayoutCmnuHor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuLeft {
            get {
                return ResourceManager.GetString("LayoutCmnuLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin Alignment 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuMargAlign {
            get {
                return ResourceManager.GetString("LayoutCmnuMargAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin Fit 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuMarginFit {
            get {
                return ResourceManager.GetString("LayoutCmnuMarginFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Right 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuRight {
            get {
                return ResourceManager.GetString("LayoutCmnuRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Alignment 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuSelectionAlignment {
            get {
                return ResourceManager.GetString("LayoutCmnuSelectionAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Fit 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuSelectionFit {
            get {
                return ResourceManager.GetString("LayoutCmnuSelectionFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align top 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuTop {
            get {
                return ResourceManager.GetString("LayoutCmnuTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Vertical 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuVert {
            get {
                return ResourceManager.GetString("LayoutCmnuVert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to Width 的本地化字符串。
        /// </summary>
        internal static string LayoutCmnuWidth {
            get {
                return ResourceManager.GetString("LayoutCmnuWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error opening layout file:  的本地化字符串。
        /// </summary>
        internal static string LayoutErrorLoad {
            get {
                return ResourceManager.GetString("LayoutErrorLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error saving layout file: 的本地化字符串。
        /// </summary>
        internal static string LayoutErrorSave {
            get {
                return ResourceManager.GetString("LayoutErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DotSpatial Print Layout 的本地化字符串。
        /// </summary>
        internal static string LayoutFormTitle {
            get {
                return ResourceManager.GetString("LayoutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert legend 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertMenuStripLegend {
            get {
                return ResourceManager.GetString("LayoutInsertMenuStripLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert scale bar 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertMenuStripScaleBar {
            get {
                return ResourceManager.GetString("LayoutInsertMenuStripScaleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert bitmap 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertToolStripBitmap {
            get {
                return ResourceManager.GetString("LayoutInsertToolStripBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert map 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertToolStripMap {
            get {
                return ResourceManager.GetString("LayoutInsertToolStripMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert north arrow 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertToolStripNorthArrow {
            get {
                return ResourceManager.GetString("LayoutInsertToolStripNorthArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert rectangle 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertToolStripRectangle {
            get {
                return ResourceManager.GetString("LayoutInsertToolStripRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert table 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertToolStripTable {
            get {
                return ResourceManager.GetString("LayoutInsertToolStripTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert text 的本地化字符串。
        /// </summary>
        internal static string LayoutInsertToolStripText {
            get {
                return ResourceManager.GetString("LayoutInsertToolStripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Print Layout 的本地化字符串。
        /// </summary>
        internal static string LayoutLoadDialogTitle {
            get {
                return ResourceManager.GetString("LayoutLoadDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom map to full extent of layers 的本地化字符串。
        /// </summary>
        internal static string LayoutMapToolStripMaxExtent {
            get {
                return ResourceManager.GetString("LayoutMapToolStripMaxExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan map 的本地化字符串。
        /// </summary>
        internal static string LayoutMapToolStripPan {
            get {
                return ResourceManager.GetString("LayoutMapToolStripPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom map to extent of data view 的本地化字符串。
        /// </summary>
        internal static string LayoutMapToolStripViewExtent {
            get {
                return ResourceManager.GetString("LayoutMapToolStripViewExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom map in 的本地化字符串。
        /// </summary>
        internal static string LayoutMapToolStripZoomIn {
            get {
                return ResourceManager.GetString("LayoutMapToolStripZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom map out 的本地化字符串。
        /// </summary>
        internal static string LayoutMapToolStripZoomOut {
            get {
                return ResourceManager.GetString("LayoutMapToolStripZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Setup 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuPageSetup {
            get {
                return ResourceManager.GetString("LayoutMenuPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Printer 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripChoosePrinter {
            get {
                return ResourceManager.GetString("LayoutMenuStripChoosePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripClose {
            get {
                return ResourceManager.GetString("LayoutMenuStripClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripDocToolbar {
            get {
                return ResourceManager.GetString("LayoutMenuStripDocToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripEdit {
            get {
                return ResourceManager.GetString("LayoutMenuStripEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as Raster 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripExportBitmap {
            get {
                return ResourceManager.GetString("LayoutMenuStripExportBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripFile {
            get {
                return ResourceManager.GetString("LayoutMenuStripFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripInsertToolbar {
            get {
                return ResourceManager.GetString("LayoutMenuStripInsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripMapToolbar {
            get {
                return ResourceManager.GetString("LayoutMenuStripMapToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripNew {
            get {
                return ResourceManager.GetString("LayoutMenuStripNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripOpen {
            get {
                return ResourceManager.GetString("LayoutMenuStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Setup 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripPageSetup {
            get {
                return ResourceManager.GetString("LayoutMenuStripPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripPrint {
            get {
                return ResourceManager.GetString("LayoutMenuStripPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripRefresh {
            get {
                return ResourceManager.GetString("LayoutMenuStripRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSave {
            get {
                return ResourceManager.GetString("LayoutMenuStripSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSaveAs {
            get {
                return ResourceManager.GetString("LayoutMenuStripSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelect {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectAll {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert to bitmap 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectConvert {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectDelete {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invert 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectInvert {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move down 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectMoveDown {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move up 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectMoveUp {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectNone {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose printer 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripSelectPrinter {
            get {
                return ResourceManager.GetString("LayoutMenuStripSelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Margin 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripShowMargin {
            get {
                return ResourceManager.GetString("LayoutMenuStripShowMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbars 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripToolbars {
            get {
                return ResourceManager.GetString("LayoutMenuStripToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripView {
            get {
                return ResourceManager.GetString("LayoutMenuStripView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to screen 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripZoomFull {
            get {
                return ResourceManager.GetString("LayoutMenuStripZoomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom in 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripZoomIn {
            get {
                return ResourceManager.GetString("LayoutMenuStripZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom out 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripZoomOut {
            get {
                return ResourceManager.GetString("LayoutMenuStripZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string LayoutMenuStripZoomToolbar {
            get {
                return ResourceManager.GetString("LayoutMenuStripZoomToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Setup 的本地化字符串。
        /// </summary>
        internal static string LayoutPageSetupTitle {
            get {
                return ResourceManager.GetString("LayoutPageSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Print Layout As 的本地化字符串。
        /// </summary>
        internal static string LayoutSaveDialogTitle {
            get {
                return ResourceManager.GetString("LayoutSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save the current print layout? 的本地化字符串。
        /// </summary>
        internal static string LayoutSaveFirst {
            get {
                return ResourceManager.GetString("LayoutSaveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to screen 的本地化字符串。
        /// </summary>
        internal static string LayoutToolStripZoomFull {
            get {
                return ResourceManager.GetString("LayoutToolStripZoomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom in 的本地化字符串。
        /// </summary>
        internal static string LayoutToolStripZoomIn {
            get {
                return ResourceManager.GetString("LayoutToolStripZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom out 的本地化字符串。
        /// </summary>
        internal static string LayoutToolStripZoomOut {
            get {
                return ResourceManager.GetString("LayoutToolStripZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin Alignment 的本地化字符串。
        /// </summary>
        internal static string LayouyCmnuMarginAlignment {
            get {
                return ResourceManager.GetString("LayouyCmnuMarginAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The wrong type of feature set was selected. Please select a line feature set. 的本地化字符串。
        /// </summary>
        internal static string LineElementWrongDataType {
            get {
                return ResourceManager.GetString("LineElementWrongDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An incompatible feature type was supplied and was not of type Line. 的本地化字符串。
        /// </summary>
        internal static string LineFeatureTypeException {
            get {
                return ResourceManager.GetString("LineFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create link 的本地化字符串。
        /// </summary>
        internal static string linkError {
            get {
                return ResourceManager.GetString("linkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output data cannot be linked to tools that generate it. 的本地化字符串。
        /// </summary>
        internal static string linkErrorCircle {
            get {
                return ResourceManager.GetString("linkErrorCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Links can only be made from data to tools. 的本地化字符串。
        /// </summary>
        internal static string linkErrorToData {
            get {
                return ResourceManager.GetString("linkErrorToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no free inputs for the this tool that take the data type attempting to be linked to it. 的本地化字符串。
        /// </summary>
        internal static string linkNoFreeInput {
            get {
                return ResourceManager.GetString("linkNoFreeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item specified was not found in this list. 的本地化字符串。
        /// </summary>
        internal static string ListItemNotFound {
            get {
                return ResourceManager.GetString("ListItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Plugins 的本地化字符串。
        /// </summary>
        internal static string LoadingPlugins {
            get {
                return ResourceManager.GetString("LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Plugins - {0}, {1}% complete. 的本地化字符串。
        /// </summary>
        internal static string LoadingPluginsPercentComplete {
            get {
                return ResourceManager.GetString("LoadingPluginsPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more of the files was not a valid data type for the map. 的本地化字符串。
        /// </summary>
        internal static string Map_OnDragDrop_Invalid {
            get {
                return ResourceManager.GetString("Map_OnDragDrop_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projection Mismatch 的本地化字符串。
        /// </summary>
        internal static string MapFrame_GlcLayerAdded_Projection_Mismatch {
            get {
                return ResourceManager.GetString("MapFrame_GlcLayerAdded_Projection_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reproject map layer to match the map coordinate system? This will not affect the source file. 的本地化字符串。
        /// </summary>
        internal static string MapFrame_GlcLayerAdded_ProjectionMismatch {
            get {
                return ResourceManager.GetString("MapFrame_GlcLayerAdded_ProjectionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projection 的本地化字符串。
        /// </summary>
        internal static string MapFrame_Projection {
            get {
                return ResourceManager.GetString("MapFrame_Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No layers are currently selectable layers active in the legend.  Select the layer or group in the legend for which selection should occur. 的本地化字符串。
        /// </summary>
        internal static string MapFunctionSelect_NoSelectableLayer {
            get {
                return ResourceManager.GetString("MapFunctionSelect_NoSelectableLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was no selected feature layer in the legend to clarify which features to delete.  Please select a layer or group in the legend. 的本地化字符串。
        /// </summary>
        internal static string MapFunctionSelect_OnKeyDown_No_Deletable_Layers {
            get {
                return ResourceManager.GetString("MapFunctionSelect_OnKeyDown_No_Deletable_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Layers 的本地化字符串。
        /// </summary>
        internal static string MapLayers {
            get {
                return ResourceManager.GetString("MapLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete elements? 的本地化字符串。
        /// </summary>
        internal static string ModelerConfirmDelete {
            get {
                return ResourceManager.GetString("ModelerConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting the selected model elements will also delete the model elements associated with them. 的本地化字符串。
        /// </summary>
        internal static string ModelerConfirmDeleteSource {
            get {
                return ResourceManager.GetString("ModelerConfirmDeleteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save the changes to %S? 的本地化字符串。
        /// </summary>
        internal static string ModelSaveCurrentModel {
            get {
                return ResourceManager.GetString("ModelSaveCurrentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add data to the model 的本地化字符串。
        /// </summary>
        internal static string ModelTipAddData {
            get {
                return ResourceManager.GetString("ModelTipAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected model elements 的本地化字符串。
        /// </summary>
        internal static string ModelTipDelete {
            get {
                return ResourceManager.GetString("ModelTipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom full extent of model 的本地化字符串。
        /// </summary>
        internal static string ModelTipFullExtent {
            get {
                return ResourceManager.GetString("ModelTipFullExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link data to tools 的本地化字符串。
        /// </summary>
        internal static string ModelTipLink {
            get {
                return ResourceManager.GetString("ModelTipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a model 的本地化字符串。
        /// </summary>
        internal static string ModelTipLoad {
            get {
                return ResourceManager.GetString("ModelTipLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new empty model 的本地化字符串。
        /// </summary>
        internal static string ModelTipNew {
            get {
                return ResourceManager.GetString("ModelTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Model 的本地化字符串。
        /// </summary>
        internal static string ModelTipRunModel {
            get {
                return ResourceManager.GetString("ModelTipRunModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the current model 的本地化字符串。
        /// </summary>
        internal static string ModelTipSave {
            get {
                return ResourceManager.GetString("ModelTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom out 的本地化字符串。
        /// </summary>
        internal static string ModelTipZoomOut {
            get {
                return ResourceManager.GetString("ModelTipZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom in 的本地化字符串。
        /// </summary>
        internal static string ModelTipZoonIn {
            get {
                return ResourceManager.GetString("ModelTipZoonIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are more than 100 unique values.  Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string MoreThan100UniqueValues {
            get {
                return ResourceManager.GetString("MoreThan100UniqueValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MW4 Project 的本地化字符串。
        /// </summary>
        internal static string MW4Project {
            get {
                return ResourceManager.GetString("MW4Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Model 的本地化字符串。
        /// </summary>
        internal static string NewModel {
            get {
                return ResourceManager.GetString("NewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None of the rows contain a value that matches the specified value. 的本地化字符串。
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The function name was not recognized as one of the standard function names. 的本地化字符串。
        /// </summary>
        internal static string NonStandardFunction {
            get {
                return ResourceManager.GetString("NonStandardFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no row in the Table. 的本地化字符串。
        /// </summary>
        internal static string NoRowInTable {
            get {
                return ResourceManager.GetString("NoRowInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This has not yet been implemented. 的本地化字符串。
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified number of significant digits (%S) is too large for this field. 的本地化字符串。
        /// </summary>
        internal static string NumberException_NumDigitsTooLarge {
            get {
                return ResourceManager.GetString("NumberException_NumDigitsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value %S was too large to encode with 18 ASCII characters. 的本地化字符串。
        /// </summary>
        internal static string NumberException_TooLarge_S {
            get {
                return ResourceManager.GetString("NumberException_TooLarge_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value %S was too small to be encoded with 18 ASCII characters. 的本地化字符串。
        /// </summary>
        internal static string NumberException_TooSmall_S {
            get {
                return ResourceManager.GetString("NumberException_TooSmall_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please only enter numeric values. 的本地化字符串。
        /// </summary>
        internal static string NumericValuesOnly {
            get {
                return ResourceManager.GetString("NumericValuesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For now, only the shapefile vector format is being supported. 的本地化字符串。
        /// </summary>
        internal static string OnlyShapefilesSupported {
            get {
                return ResourceManager.GetString("OnlyShapefilesSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity controls how transparent the item is.  A 0 is fully transparent, while 1 is fully opaque. 的本地化字符串。
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity should be a floating decimal point between 0 and 1. 的本地化字符串。
        /// </summary>
        internal static string OpacityInvalid {
            get {
                return ResourceManager.GetString("OpacityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painting Color Scheme To Bitmap 的本地化字符串。
        /// </summary>
        internal static string PaintingColorScheme {
            get {
                return ResourceManager.GetString("PaintingColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painting Hillshade To Bitmap 的本地化字符串。
        /// </summary>
        internal static string PaintingHillshade {
            get {
                return ResourceManager.GetString("PaintingHillshade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid parameter value 的本地化字符串。
        /// </summary>
        internal static string ParameterInvalid {
            get {
                return ResourceManager.GetString("ParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter is valid 的本地化字符串。
        /// </summary>
        internal static string ParameterValid {
            get {
                return ResourceManager.GetString("ParameterValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value you entered could not be parsed into a %S.  Make sure the value is in the valid range. 的本地化字符串。
        /// </summary>
        internal static string ParseFailed_S {
            get {
                return ResourceManager.GetString("ParseFailed_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apps 的本地化字符串。
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The desired length of %S1 was too long.  The total length was %S2 and the offset was %S3. 的本地化字符串。
        /// </summary>
        internal static string PngInsuficientLengthException {
            get {
                return ResourceManager.GetString("PngInsuficientLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The beginning eight bytes of the specified file did not match the png signature. 的本地化字符串。
        /// </summary>
        internal static string PngInvalidSignatureException {
            get {
                return ResourceManager.GetString("PngInvalidSignatureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An incompatible feature type was supplied and was not of type Point. 的本地化字符串。
        /// </summary>
        internal static string PointFeatureTypeException {
            get {
                return ResourceManager.GetString("PointFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Holes must not contain null elements 的本地化字符串。
        /// </summary>
        internal static string PolygonException_HoleElementNull {
            get {
                return ResourceManager.GetString("PolygonException_HoleElementNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell is empty but holes are not 的本地化字符串。
        /// </summary>
        internal static string PolygonException_ShellEmptyButHolesNot {
            get {
                return ResourceManager.GetString("PolygonException_ShellEmptyButHolesNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An incompatible feature type was supplied and was not of type polygon. 的本地化字符串。
        /// </summary>
        internal static string PolygonFeatureTypeException {
            get {
                return ResourceManager.GetString("PolygonFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project File 的本地化字符串。
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antialiasing 的本地化字符串。
        /// </summary>
        internal static string prop_alias {
            get {
                return ResourceManager.GetString("prop_alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align 的本地化字符串。
        /// </summary>
        internal static string prop_align {
            get {
                return ResourceManager.GetString("prop_align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrow Style 的本地化字符串。
        /// </summary>
        internal static string prop_arrow_style {
            get {
                return ResourceManager.GetString("prop_arrow_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border Width 的本地化字符串。
        /// </summary>
        internal static string prop_borderwidth {
            get {
                return ResourceManager.GetString("prop_borderwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of Breaks 的本地化字符串。
        /// </summary>
        internal static string prop_breakcount {
            get {
                return ResourceManager.GetString("prop_breakcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break at Zero 的本地化字符串。
        /// </summary>
        internal static string prop_breakzero {
            get {
                return ResourceManager.GetString("prop_breakzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness 的本地化字符串。
        /// </summary>
        internal static string prop_brightness {
            get {
                return ResourceManager.GetString("prop_brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string prop_color {
            get {
                return ResourceManager.GetString("prop_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contrast 的本地化字符串。
        /// </summary>
        internal static string prop_contrast {
            get {
                return ResourceManager.GetString("prop_contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Header 的本地化字符串。
        /// </summary>
        internal static string prop_displayheader {
            get {
                return ResourceManager.GetString("prop_displayheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw Tiles 的本地化字符串。
        /// </summary>
        internal static string prop_drawtiles {
            get {
                return ResourceManager.GetString("prop_drawtiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        internal static string prop_filename {
            get {
                return ResourceManager.GetString("prop_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        internal static string prop_font {
            get {
                return ResourceManager.GetString("prop_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Font 的本地化字符串。
        /// </summary>
        internal static string prop_groupfont {
            get {
                return ResourceManager.GetString("prop_groupfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Groups 的本地化字符串。
        /// </summary>
        internal static string prop_groups {
            get {
                return ResourceManager.GetString("prop_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header Fill Color 的本地化字符串。
        /// </summary>
        internal static string prop_header_fill_color {
            get {
                return ResourceManager.GetString("prop_header_fill_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header Font 的本地化字符串。
        /// </summary>
        internal static string prop_headerfont {
            get {
                return ResourceManager.GetString("prop_headerfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        internal static string prop_height {
            get {
                return ResourceManager.GetString("prop_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Padding 的本地化字符串。
        /// </summary>
        internal static string prop_horizontalpadding {
            get {
                return ResourceManager.GetString("prop_horizontalpadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layers 的本地化字符串。
        /// </summary>
        internal static string prop_layers {
            get {
                return ResourceManager.GetString("prop_layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        internal static string prop_location {
            get {
                return ResourceManager.GetString("prop_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Map 的本地化字符串。
        /// </summary>
        internal static string prop_mainmap {
            get {
                return ResourceManager.GetString("prop_mainmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        internal static string prop_map {
            get {
                return ResourceManager.GetString("prop_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Row Height 的本地化字符串。
        /// </summary>
        internal static string prop_minrowheight {
            get {
                return ResourceManager.GetString("prop_minrowheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string prop_name {
            get {
                return ResourceManager.GetString("prop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of Columns 的本地化字符串。
        /// </summary>
        internal static string prop_numcol {
            get {
                return ResourceManager.GetString("prop_numcol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider 的本地化字符串。
        /// </summary>
        internal static string prop_provider {
            get {
                return ResourceManager.GetString("prop_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preserve Aspect Ratio 的本地化字符串。
        /// </summary>
        internal static string prop_ratio {
            get {
                return ResourceManager.GetString("prop_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string prop_role {
            get {
                return ResourceManager.GetString("prop_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation 的本地化字符串。
        /// </summary>
        internal static string prop_rotation {
            get {
                return ResourceManager.GetString("prop_rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale, 1: 的本地化字符串。
        /// </summary>
        internal static string prop_scale {
            get {
                return ResourceManager.GetString("prop_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Scale 的本地化字符串。
        /// </summary>
        internal static string prop_showscale {
            get {
                return ResourceManager.GetString("prop_showscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string prop_size {
            get {
                return ResourceManager.GetString("prop_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string prop_text {
            get {
                return ResourceManager.GetString("prop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thumbnail Height 的本地化字符串。
        /// </summary>
        internal static string prop_thumbnail_height {
            get {
                return ResourceManager.GetString("prop_thumbnail_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thumbnail Width 的本地化字符串。
        /// </summary>
        internal static string prop_thumbnail_width {
            get {
                return ResourceManager.GetString("prop_thumbnail_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Units 的本地化字符串。
        /// </summary>
        internal static string prop_unit {
            get {
                return ResourceManager.GetString("prop_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Map Area 的本地化字符串。
        /// </summary>
        internal static string prop_updatemaparea {
            get {
                return ResourceManager.GetString("prop_updatemaparea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        internal static string prop_width {
            get {
                return ResourceManager.GetString("prop_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of bytes should be 4 * rows * cols since only ARGB format is supported. 的本地化字符串。
        /// </summary>
        internal static string PyramidByteMismatchException {
            get {
                return ResourceManager.GetString("PyramidByteMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The header has not been defined for the image scale you are attempting to access. 的本地化字符串。
        /// </summary>
        internal static string PyramidHeaderException {
            get {
                return ResourceManager.GetString("PyramidHeaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rows or columns would extend beyond the specified number of columns or rows for the specified scale. 的本地化字符串。
        /// </summary>
        internal static string PyramidOutOfBoundsException {
            get {
                return ResourceManager.GetString("PyramidOutOfBoundsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To work with anything other than an in-memory raster window, you must first cast this raster to the correct data format. 的本地化字符串。
        /// </summary>
        internal static string RasterRequiresCast {
            get {
                return ResourceManager.GetString("RasterRequiresCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified rasters must have their cell sizes dimensioned. 的本地化字符串。
        /// </summary>
        internal static string RastersMustHaveCellSize {
            get {
                return ResourceManager.GetString("RastersMustHaveCellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rasters must have equally sized cells to use this method. 的本地化字符串。
        /// </summary>
        internal static string RastersNeedSameCellSize {
            get {
                return ResourceManager.GetString("RastersNeedSameCellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified raster would be too large to store in memory. 的本地化字符串。
        /// </summary>
        internal static string RasterTooLarge {
            get {
                return ResourceManager.GetString("RasterTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading values from %S 的本地化字符串。
        /// </summary>
        internal static string ReadingValuesFrom_S {
            get {
                return ResourceManager.GetString("ReadingValuesFrom_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list is currently set to read-only, and cannot be modified. 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyList {
            get {
                return ResourceManager.GetString("ReadOnlyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove the fields? 的本地化字符串。
        /// </summary>
        internal static string RemoveFields {
            get {
                return ResourceManager.GetString("RemoveFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The root n-th root is incorrect 的本地化字符串。
        /// </summary>
        internal static string RootNthRootIncorrect {
            get {
                return ResourceManager.GetString("RootNthRootIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified feature was not found in the feature list and could not be selected. 的本地化字符串。
        /// </summary>
        internal static string Selection_FeatureNotFound {
            get {
                return ResourceManager.GetString("Selection_FeatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show page numbers 的本地化字符串。
        /// </summary>
        internal static string ShowPageNumbers {
            get {
                return ResourceManager.GetString("ShowPageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify an attribute field to use for classification before using this feature. 的本地化字符串。
        /// </summary>
        internal static string SpecifyField {
            get {
                return ResourceManager.GetString("SpecifyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument startIndex was too large to read the requested number of bytes from byteArray. 的本地化字符串。
        /// </summary>
        internal static string StartIndexTooLarge {
            get {
                return ResourceManager.GetString("StartIndexTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fields that are the string datatype cannot be converted to a raster.  Do you wish to use the FID value instead? 的本地化字符串。
        /// </summary>
        internal static string StringFieldInvalid {
            get {
                return ResourceManager.GetString("StringFieldInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported Files 的本地化字符串。
        /// </summary>
        internal static string SupportedFiles {
            get {
                return ResourceManager.GetString("SupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The tool cannot be run because one or more of its parameters is not set. 的本地化字符串。
        /// </summary>
        internal static string ToolSetupIncorectly {
            get {
                return ResourceManager.GetString("ToolSetupIncorectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There were too many closing brackets in the string expression. 的本地化字符串。
        /// </summary>
        internal static string TooManyClosingBrackets {
            get {
                return ResourceManager.GetString("TooManyClosingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are too many Unique values. 的本地化字符串。
        /// </summary>
        internal static string TooManyUniqueValues {
            get {
                return ResourceManager.GetString("TooManyUniqueValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assigned depths do not match 的本地化字符串。
        /// </summary>
        internal static string TopologyException_Depth {
            get {
                return ResourceManager.GetString("TopologyException_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To save the calulated value press the Apply button 的本地化字符串。
        /// </summary>
        internal static string ToSave {
            get {
                return ResourceManager.GetString("ToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing values to %S 的本地化字符串。
        /// </summary>
        internal static string WritingValues_S {
            get {
                return ResourceManager.GetString("WritingValues_S", resourceCulture);
            }
        }
    }
}
