//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VastGIS.RealEstate.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VastGIS.RealEstate.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [vg_areacodes] values(2, &apos;北京市&apos;, &apos;110000&apos;, 1);
        ///insert into [vg_areacodes] values(3, &apos;市辖区&apos;, &apos;110100&apos;, 2);
        ///insert into [vg_areacodes] values(4, &apos;东城区&apos;, &apos;110101&apos;, 3);
        ///insert into [vg_areacodes] values(5, &apos;西城区&apos;, &apos;110102&apos;, 3);
        ///insert into [vg_areacodes] values(6, &apos;朝阳区&apos;, &apos;110105&apos;, 3);
        ///insert into [vg_areacodes] values(7, &apos;丰台区&apos;, &apos;110106&apos;, 3);
        ///insert into [vg_areacodes] values(8, &apos;石景山区&apos;, &apos;110107&apos;, 3);
        ///insert into [vg_areacodes] values(9, &apos;海淀区&apos;, &apos;110108&apos;, 3);
        ///insert into [vg_areacodes] values(10, &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Areacodes {
            get {
                return ResourceManager.GetString("Areacodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;vg_cadcodes&quot; (&quot;id&quot;, &quot;xh&quot;, &quot;sfcy&quot;, &quot;tc&quot;, &quot;cassdm&quot;, &quot;txlx&quot;, &quot;xtc&quot;, &quot;ysdm&quot;, &quot;yslx&quot;, &quot;yszl&quot;) VALUES (1, &apos;C000&apos;, 1, &apos;KZD&apos;, &apos;C11233&apos;, &apos;INSERT&apos;, &apos;控制点&apos;, &apos;C00101010&apos;, &apos;点&apos;, 0);
        ///INSERT INTO &quot;vg_cadcodes&quot; (&quot;id&quot;, &quot;xh&quot;, &quot;sfcy&quot;, &quot;tc&quot;, &quot;cassdm&quot;, &quot;txlx&quot;, &quot;xtc&quot;, &quot;ysdm&quot;, &quot;yslx&quot;, &quot;yszl&quot;) VALUES (2, &apos;C182&apos;, 1, &apos;KZD&apos;, &apos;131100&apos;, &apos;INSERT&apos;, &apos;控制点&apos;, &apos;11010211&apos;, &apos;点&apos;, 0);
        ///INSERT INTO &quot;vg_cadcodes&quot; (&quot;id&quot;, &quot;xh&quot;, &quot;sfcy&quot;, &quot;tc&quot;, &quot;cassdm&quot;, &quot;txlx&quot;, &quot;xtc&quot;, &quot;ysdm&quot;, &quot;yslx&quot;, &quot;yszl&quot;) VALUES (3, &apos;C183&apos;, 1, &apos;KZD&apos;, &apos;131200&apos;, &apos;INSERT&apos;, &....
        /// </summary>
        internal static string Casscodes {
            get {
                return ResourceManager.GetString("Casscodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;JXLXZD&apos;, &apos;界线类型字典表&apos;);
        ///insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;JXXZZD&apos;, &apos;界线性质字典表&apos;);
        ///insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;JZXWZZD&apos;, &apos;界址线位置&apos;);
        ///insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;JBLXZD&apos;, &apos;界标类型&apos;);
        ///insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;JZDLXZD&apos;, &apos;界址点类型字典表&apos;);
        ///insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;SFZD&apos;, &apos;是否字典表&apos;);
        ///insert into [vg_dictoryname](&apos;ZDMC&apos;,&apos;ZDSM&apos;) values(&apos;MJDWZD&apos;, &apos;面积单位字典表&apos;);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [vg_objectysdm] values(31, &apos;1001010000&apos;, &apos;行政区&apos;, 0, &apos;XZQ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(32, &apos;1001020000&apos;, &apos;行政区界线&apos;, 0, &apos;XZQJX&apos;, null, 1);
        ///insert into [vg_objectysdm] values(33, &apos;1001030000&apos;, &apos;行政区注记&apos;, 0, &apos;XZQZJ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(34, &apos;1002000000&apos;, &apos;地籍区&apos;, 0, &apos;DJQ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(35, &apos;1003000000&apos;, &apos;地籍子区&apos;, 0, &apos;DJZQ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(36, &apos;6001010000&apos;, &apos;宗地&apos;, 0, &apos;ZDJBXX&apos;, null, 1);
        ///insert into [v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ysdm {
            get {
                return ResourceManager.GetString("Ysdm", resourceCulture);
            }
        }
    }
}
