//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VastGIS.RealEstate.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VastGIS.RealEstate.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [vg_areacode] values(2, &apos;北京市&apos;, &apos;110000&apos;, 1);
        ///insert into [vg_areacode] values(3, &apos;市辖区&apos;, &apos;110100&apos;, 2);
        ///insert into [vg_areacode] values(4, &apos;东城区&apos;, &apos;110101&apos;, 3);
        ///insert into [vg_areacode] values(5, &apos;西城区&apos;, &apos;110102&apos;, 3);
        ///insert into [vg_areacode] values(6, &apos;朝阳区&apos;, &apos;110105&apos;, 3);
        ///insert into [vg_areacode] values(7, &apos;丰台区&apos;, &apos;110106&apos;, 3);
        ///insert into [vg_areacode] values(8, &apos;石景山区&apos;, &apos;110107&apos;, 3);
        ///insert into [vg_areacode] values(9, &apos;海淀区&apos;, &apos;110108&apos;, 3);
        ///insert into [vg_areacode] values(10, &apos;门头沟区&apos;, &apos;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Areacode {
            get {
                return ResourceManager.GetString("Areacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [vg_objectitem] ([YSDM], [YSMC], [YSBM], [SFKJ], [YSLX], [SM]) VALUES (&apos;1000000000&apos;, &apos;基础地理信息要素&apos;, &apos;&apos;, 1, &apos;&apos;, &apos;&apos;);
        ///INSERT INTO [vg_objectitem] ([YSDM], [YSMC], [YSBM], [SFKJ], [YSLX], [SM]) VALUES (&apos;1001000000&apos;, &apos;境界与政区&apos;, &apos;&apos;, 1, &apos;&apos;, &apos;&apos;);
        ///INSERT INTO [vg_objectitem] ([YSDM], [YSMC], [YSBM], [SFKJ], [YSLX], [SM]) VALUES (&apos;1001010000&apos;, &apos;行政区&apos;, &apos;XZQ&apos;, 0, &apos;空间&apos;, &apos;《基础地理信息要素分类与代码》（GB/T13923－2006）的扩展&apos;);
        ///INSERT INTO [vg_objectitem] ([YSDM], [YSMC], [YSBM], [SFKJ], [YSLX], [SM]) VALUES (&apos;1001020000&apos;, &apos;行政区界线 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bdcysdm {
            get {
                return ResourceManager.GetString("Bdcysdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;vg_cadcode&quot; (&quot;id&quot;, &quot;xh&quot;, &quot;sfcy&quot;, &quot;tc&quot;, &quot;cassdm&quot;, &quot;txlx&quot;, &quot;xtc&quot;, &quot;ysdm&quot;, &quot;yslx&quot;, &quot;yszl&quot;) VALUES (1, &apos;C000&apos;, 1, &apos;KZD&apos;, &apos;C11233&apos;, &apos;INSERT&apos;, &apos;控制点&apos;, &apos;C00101010&apos;, &apos;点&apos;, 0);
        ///INSERT INTO &quot;vg_cadcode&quot; (&quot;id&quot;, &quot;xh&quot;, &quot;sfcy&quot;, &quot;tc&quot;, &quot;cassdm&quot;, &quot;txlx&quot;, &quot;xtc&quot;, &quot;ysdm&quot;, &quot;yslx&quot;, &quot;yszl&quot;) VALUES (2, &apos;C182&apos;, 1, &apos;KZD&apos;, &apos;131100&apos;, &apos;INSERT&apos;, &apos;控制点&apos;, &apos;11010211&apos;, &apos;点&apos;, 0);
        ///INSERT INTO &quot;vg_cadcode&quot; (&quot;id&quot;, &quot;xh&quot;, &quot;sfcy&quot;, &quot;tc&quot;, &quot;cassdm&quot;, &quot;txlx&quot;, &quot;xtc&quot;, &quot;ysdm&quot;, &quot;yslx&quot;, &quot;yszl&quot;) VALUES (3, &apos;C183&apos;, 1, &apos;KZD&apos;, &apos;131200&apos;, &apos;INSERT&apos;, &apo....
        /// </summary>
        internal static string Casscode {
            get {
                return ResourceManager.GetString("Casscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [vg_dictoryname] ([Id], [ZDMC], [ZDSM]) VALUES (1, &apos;JXLXZD&apos;, &apos;界线类型字典表&apos;);
        ///INSERT INTO [vg_dictoryname] ([Id], [ZDMC], [ZDSM]) VALUES (2, &apos;JXXZZD&apos;, &apos;界线性质字典表&apos;);
        ///INSERT INTO [vg_dictoryname] ([Id], [ZDMC], [ZDSM]) VALUES (3, &apos;JZXWZZD&apos;, &apos;界址线位置字典表&apos;);
        ///INSERT INTO [vg_dictoryname] ([Id], [ZDMC], [ZDSM]) VALUES (4, &apos;JBLXZD&apos;, &apos;界标类型字典表&apos;);
        ///INSERT INTO [vg_dictoryname] ([Id], [ZDMC], [ZDSM]) VALUES (5, &apos;JZDLXZD&apos;, &apos;界址点类型字典表&apos;);
        ///INSERT INTO [vg_dictoryname] ([Id], [ZDMC], [ZDSM]) VALUES (6, &apos;SFZD&apos;, &apos;是否字典表&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [vg_setting] ([Id], [CSMC], [CSZ]) VALUES (2, &apos;XZQHDM&apos;, &apos;320200&apos;);
        ///INSERT INTO [vg_setting] ([Id], [CSMC], [CSZ]) VALUES (3, &apos;WXDCY&apos;, &apos;未见空间&apos;);
        ///INSERT INTO [vg_setting] ([Id], [CSMC], [CSZ]) VALUES (4, &apos;WXCLY&apos;, &apos;未见空间&apos;);
        ///INSERT INTO [vg_setting] ([Id], [CSMC], [CSZ]) VALUES (5, &apos;DXTWZSXSB&apos;, &apos;[{&quot;name&quot;:&quot;居民地楼层识别&quot;,&quot;assigntype&quot;:&quot;Integer&quot;,&quot;assigntable&quot;:&quot;DXTJMDM&quot;,&quot;assignfield&quot;:&quot;FSXX1&quot;,&quot;texttable&quot;:&quot;DXTZJZJ&quot;,&quot;textfield&quot;:&quot;Wbnr&quot;,&quot;whereclause&quot;:&quot;[a].TC=&apos;&apos;ZJ&apos;&apos;&quot;,&quot;assignvalues&quot;:null},{&quot;name&quot;:&quot;居民地材质识别&quot;,&quot;assignt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Szcsh {
            get {
                return ResourceManager.GetString("Szcsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [vg_objectysdm] values(31, &apos;1001010000&apos;, &apos;行政区&apos;, 0, &apos;XZQ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(32, &apos;1001020000&apos;, &apos;行政区界线&apos;, 0, &apos;XZQJX&apos;, null, 1);
        ///insert into [vg_objectysdm] values(33, &apos;1001030000&apos;, &apos;行政区注记&apos;, 0, &apos;XZQZJ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(34, &apos;1002000000&apos;, &apos;地籍区&apos;, 0, &apos;DJQ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(35, &apos;1003000000&apos;, &apos;地籍子区&apos;, 0, &apos;DJZQ&apos;, null, 1);
        ///insert into [vg_objectysdm] values(36, &apos;6001010000&apos;, &apos;宗地&apos;, 0, &apos;ZDJBXX&apos;, null, 1);
        ///insert into [v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ysdm {
            get {
                return ResourceManager.GetString("Ysdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into [vg_fieldinfo] values(1, &apos;XZQ&apos;, 1, &apos;标识码&apos;, &apos;ID&apos;, &apos;Int&apos;, 10, 0, &apos;&apos;, &apos;M&apos;, &apos;&apos;);
        ///insert into [vg_fieldinfo] values(2, &apos;XZQ&apos;, 2, &apos;要素代码&apos;, &apos;YSDM&apos;, &apos;Char&apos;, 10, 0, &apos;&apos;, &apos;M&apos;, &apos;&apos;);
        ///insert into [vg_fieldinfo] values(3, &apos;XZQ&apos;, 3, &apos;行政区代码&apos;, &apos;XZQDM&apos;, &apos;Char&apos;, 12, 0, &apos;&apos;, &apos;M&apos;, &apos;&apos;);
        ///insert into [vg_fieldinfo] values(4, &apos;XZQ&apos;, 4, &apos;行政区名称&apos;, &apos;XZQMC&apos;, &apos;Char&apos;, 100, 0, &apos;&apos;, &apos;M&apos;, &apos;&apos;);
        ///insert into [vg_fieldinfo] values(5, &apos;XZQ&apos;, 5, &apos;行政区面积&apos;, &apos;XZQMJ&apos;, &apos;Float&apos;, 15, 2, &apos;&apos;, &apos;C&apos;, &apos;&apos;);
        ///insert into [vg_fieldinfo] values(6, &apos;XZQJX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zdxx {
            get {
                return ResourceManager.GetString("Zdxx", resourceCulture);
            }
        }
    }
}
