//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.33440。
// 
namespace VastGIS.Services.Serialization.Legacy
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Layers
    {

        private LayersLayer[] layerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Layer", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LayersLayer[] Layer
        {
            get
            {
                return this.layerField;
            }
            set
            {
                this.layerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayer
    {

        private LayersLayerShapefileClass[] shapefileClassField;

        private LayersLayerImageClass[] imageClassField;

        private string layerTypeField;

        private string layerNameField;

        private string layerVisibleField;

        private string layerKeyField;

        private string filenameField;

        private string dynamicVisibilityField;

        private string minVisibleScaleField;

        private string maxVisibleScaleField;

        private string nameField;

        private string tagField;

        private string expandedField;

        private string handleField;

        private string positionInGroupField;

        private string groupIndexField;

        private string groupNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShapefileClass", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LayersLayerShapefileClass[] ShapefileClass
        {
            get
            {
                return this.shapefileClassField;
            }
            set
            {
                this.shapefileClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageClass", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LayersLayerImageClass[] ImageClass
        {
            get
            {
                return this.imageClassField;
            }
            set
            {
                this.imageClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayerType
        {
            get
            {
                return this.layerTypeField;
            }
            set
            {
                this.layerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayerName
        {
            get
            {
                return this.layerNameField;
            }
            set
            {
                this.layerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayerVisible
        {
            get
            {
                return this.layerVisibleField;
            }
            set
            {
                this.layerVisibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LayerKey
        {
            get
            {
                return this.layerKeyField;
            }
            set
            {
                this.layerKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DynamicVisibility
        {
            get
            {
                return this.dynamicVisibilityField;
            }
            set
            {
                this.dynamicVisibilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinVisibleScale
        {
            get
            {
                return this.minVisibleScaleField;
            }
            set
            {
                this.minVisibleScaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxVisibleScale
        {
            get
            {
                return this.maxVisibleScaleField;
            }
            set
            {
                this.maxVisibleScaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expanded
        {
            get
            {
                return this.expandedField;
            }
            set
            {
                this.expandedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Handle
        {
            get
            {
                return this.handleField;
            }
            set
            {
                this.handleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PositionInGroup
        {
            get
            {
                return this.positionInGroupField;
            }
            set
            {
                this.positionInGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GroupIndex
        {
            get
            {
                return this.groupIndexField;
            }
            set
            {
                this.groupIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GroupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayerShapefileClass
    {

        private string shapefileCategoriesClassField;

        private LayersLayerShapefileClassDefaultDrawingOptions[] defaultDrawingOptionsField;

        private LabelsClass[] labelsClassField;

        private LayersLayerShapefileClassChartsClass[] chartsClassField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShapefileCategoriesClass
        {
            get
            {
                return this.shapefileCategoriesClassField;
            }
            set
            {
                this.shapefileCategoriesClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefaultDrawingOptions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LayersLayerShapefileClassDefaultDrawingOptions[] DefaultDrawingOptions
        {
            get
            {
                return this.defaultDrawingOptionsField;
            }
            set
            {
                this.defaultDrawingOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LabelsClass")]
        public LabelsClass[] LabelsClass
        {
            get
            {
                return this.labelsClassField;
            }
            set
            {
                this.labelsClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChartsClass", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LayersLayerShapefileClassChartsClass[] ChartsClass
        {
            get
            {
                return this.chartsClassField;
            }
            set
            {
                this.chartsClassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayerShapefileClassDefaultDrawingOptions
    {

        private LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClass[] linePatternClassField;

        private string fillBgColorField;

        private string fillColorField;

        private string lineColorField;

        private string pointShapeRatioField;

        private string pointSizeField;

        private string fillBgTransparentField;

        private string fillHatchStyleField;

        private string fillTransparencyField;

        private string fillTypeField;

        private string fillColor2Field;

        private string scaleXField;

        private string scaleYField;

        private string fillVisibleField;

        private string fillGradientBoundsField;

        private string fillGradientTypeField;

        private string pointNumSidesField;

        private string pointShapeTypeField;

        private string fontNameField;

        private string pointCharcterField;

        private string pointSymbolTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinePatternClass", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClass[] LinePatternClass
        {
            get
            {
                return this.linePatternClassField;
            }
            set
            {
                this.linePatternClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillBgColor
        {
            get
            {
                return this.fillBgColorField;
            }
            set
            {
                this.fillBgColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillColor
        {
            get
            {
                return this.fillColorField;
            }
            set
            {
                this.fillColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LineColor
        {
            get
            {
                return this.lineColorField;
            }
            set
            {
                this.lineColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PointShapeRatio
        {
            get
            {
                return this.pointShapeRatioField;
            }
            set
            {
                this.pointShapeRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PointSize
        {
            get
            {
                return this.pointSizeField;
            }
            set
            {
                this.pointSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillBgTransparent
        {
            get
            {
                return this.fillBgTransparentField;
            }
            set
            {
                this.fillBgTransparentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillHatchStyle
        {
            get
            {
                return this.fillHatchStyleField;
            }
            set
            {
                this.fillHatchStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillTransparency
        {
            get
            {
                return this.fillTransparencyField;
            }
            set
            {
                this.fillTransparencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillType
        {
            get
            {
                return this.fillTypeField;
            }
            set
            {
                this.fillTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillColor2
        {
            get
            {
                return this.fillColor2Field;
            }
            set
            {
                this.fillColor2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ScaleX
        {
            get
            {
                return this.scaleXField;
            }
            set
            {
                this.scaleXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ScaleY
        {
            get
            {
                return this.scaleYField;
            }
            set
            {
                this.scaleYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillVisible
        {
            get
            {
                return this.fillVisibleField;
            }
            set
            {
                this.fillVisibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillGradientBounds
        {
            get
            {
                return this.fillGradientBoundsField;
            }
            set
            {
                this.fillGradientBoundsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FillGradientType
        {
            get
            {
                return this.fillGradientTypeField;
            }
            set
            {
                this.fillGradientTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PointNumSides
        {
            get
            {
                return this.pointNumSidesField;
            }
            set
            {
                this.pointNumSidesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PointShapeType
        {
            get
            {
                return this.pointShapeTypeField;
            }
            set
            {
                this.pointShapeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FontName
        {
            get
            {
                return this.fontNameField;
            }
            set
            {
                this.fontNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PointCharcter
        {
            get
            {
                return this.pointCharcterField;
            }
            set
            {
                this.pointCharcterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PointSymbolType
        {
            get
            {
                return this.pointSymbolTypeField;
            }
            set
            {
                this.pointSymbolTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClass
    {

        private LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClassLineSegmentsLineSegmentClass[][] lineSegmentsField;

        private string keyField;

        private string transparencyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LineSegmentClass", typeof(LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClassLineSegmentsLineSegmentClass), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClassLineSegmentsLineSegmentClass[][] LineSegments
        {
            get
            {
                return this.lineSegmentsField;
            }
            set
            {
                this.lineSegmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Transparency
        {
            get
            {
                return this.transparencyField;
            }
            set
            {
                this.transparencyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayerShapefileClassDefaultDrawingOptionsLinePatternClassLineSegmentsLineSegmentClass
    {

        private string lineTypeField;

        private string colorField;

        private string markerOutlineColorField;

        private string lineWidthField;

        private string markerSizeField;

        private string markerIntervalField;

        private string markerOffsetField;

        private string lineStyleField;

        private string markerField;

        private string markerOrientationField;

        private string markerFlipFirstField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LineType
        {
            get
            {
                return this.lineTypeField;
            }
            set
            {
                this.lineTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarkerOutlineColor
        {
            get
            {
                return this.markerOutlineColorField;
            }
            set
            {
                this.markerOutlineColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LineWidth
        {
            get
            {
                return this.lineWidthField;
            }
            set
            {
                this.lineWidthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarkerSize
        {
            get
            {
                return this.markerSizeField;
            }
            set
            {
                this.markerSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarkerInterval
        {
            get
            {
                return this.markerIntervalField;
            }
            set
            {
                this.markerIntervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarkerOffset
        {
            get
            {
                return this.markerOffsetField;
            }
            set
            {
                this.markerOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LineStyle
        {
            get
            {
                return this.lineStyleField;
            }
            set
            {
                this.lineStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Marker
        {
            get
            {
                return this.markerField;
            }
            set
            {
                this.markerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarkerOrientation
        {
            get
            {
                return this.markerOrientationField;
            }
            set
            {
                this.markerOrientationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarkerFlipFirst
        {
            get
            {
                return this.markerFlipFirstField;
            }
            set
            {
                this.markerFlipFirstField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class LabelsClass
    {

        private string alignmentField;

        private string fontColorField;

        private string frameBackColor2Field;

        private string frameGradientModeField;

        private string frameVisibleField;

        private string generatedField;

        private string maxVisibleScaleField;

        private string autoOffsetField;

        private string dynamicVisibilityField;

        private string avoidCollisionsField;

        private string positioningField;

        private string expressionField;

        private string frameBackColorField;

        private string fontNameField;

        private string haloColorField;

        private string haloVisibleField;

        private string offsetYField;

        private string shadowVisibleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alignment
        {
            get
            {
                return this.alignmentField;
            }
            set
            {
                this.alignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FontColor
        {
            get
            {
                return this.fontColorField;
            }
            set
            {
                this.fontColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameBackColor2
        {
            get
            {
                return this.frameBackColor2Field;
            }
            set
            {
                this.frameBackColor2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameGradientMode
        {
            get
            {
                return this.frameGradientModeField;
            }
            set
            {
                this.frameGradientModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameVisible
        {
            get
            {
                return this.frameVisibleField;
            }
            set
            {
                this.frameVisibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Generated
        {
            get
            {
                return this.generatedField;
            }
            set
            {
                this.generatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxVisibleScale
        {
            get
            {
                return this.maxVisibleScaleField;
            }
            set
            {
                this.maxVisibleScaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AutoOffset
        {
            get
            {
                return this.autoOffsetField;
            }
            set
            {
                this.autoOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DynamicVisibility
        {
            get
            {
                return this.dynamicVisibilityField;
            }
            set
            {
                this.dynamicVisibilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AvoidCollisions
        {
            get
            {
                return this.avoidCollisionsField;
            }
            set
            {
                this.avoidCollisionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Positioning
        {
            get
            {
                return this.positioningField;
            }
            set
            {
                this.positioningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameBackColor
        {
            get
            {
                return this.frameBackColorField;
            }
            set
            {
                this.frameBackColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FontName
        {
            get
            {
                return this.fontNameField;
            }
            set
            {
                this.fontNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HaloColor
        {
            get
            {
                return this.haloColorField;
            }
            set
            {
                this.haloColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HaloVisible
        {
            get
            {
                return this.haloVisibleField;
            }
            set
            {
                this.haloVisibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OffsetY
        {
            get
            {
                return this.offsetYField;
            }
            set
            {
                this.offsetYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShadowVisible
        {
            get
            {
                return this.shadowVisibleField;
            }
            set
            {
                this.shadowVisibleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayerShapefileClassChartsClass
    {

        private string valuesFontNameField;

        private string visibleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValuesFontName
        {
            get
            {
                return this.valuesFontNameField;
            }
            set
            {
                this.valuesFontNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class LayersLayerImageClass
    {

        private LabelsClass[] labelsClassField;

        private string keyField;

        private string setToGreyField;

        private string transparencyColorField;

        private string transparencyColor2Field;

        private string useTransparencyColorField;

        private string transparencyPercentField;

        private string downsamplingModeField;

        private string upsamplingModeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LabelsClass")]
        public LabelsClass[] LabelsClass
        {
            get
            {
                return this.labelsClassField;
            }
            set
            {
                this.labelsClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SetToGrey
        {
            get
            {
                return this.setToGreyField;
            }
            set
            {
                this.setToGreyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransparencyColor
        {
            get
            {
                return this.transparencyColorField;
            }
            set
            {
                this.transparencyColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransparencyColor2
        {
            get
            {
                return this.transparencyColor2Field;
            }
            set
            {
                this.transparencyColor2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UseTransparencyColor
        {
            get
            {
                return this.useTransparencyColorField;
            }
            set
            {
                this.useTransparencyColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransparencyPercent
        {
            get
            {
                return this.transparencyPercentField;
            }
            set
            {
                this.transparencyPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DownsamplingMode
        {
            get
            {
                return this.downsamplingModeField;
            }
            set
            {
                this.downsamplingModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UpsamplingMode
        {
            get
            {
                return this.upsamplingModeField;
            }
            set
            {
                this.upsamplingModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Plugin
    {

        private string settingsStringField;

        private string keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SettingsString
        {
            get
            {
                return this.settingsStringField;
            }
            set
            {
                this.settingsStringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Image
    {

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VastGIS
    {

        private VastGISMapWinGIS[] mapWinGISField;

        private VastGISVastGIS1[] vastGIS1Field;

        private string nameField;

        private string typeField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MapWinGIS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VastGISMapWinGIS[] MapWinGIS
        {
            get
            {
                return this.mapWinGISField;
            }
            set
            {
                this.mapWinGISField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VastGIS1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VastGISVastGIS1[] VastGIS1
        {
            get
            {
                return this.vastGIS1Field;
            }
            set
            {
                this.vastGIS1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISMapWinGIS
    {

        private VastGISMapWinGISMapState[] mapStateField;

        private LayersLayer[][] layersField;

        private string ocxVersionField;

        private string fileTypeField;

        private string fileVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MapState", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VastGISMapWinGISMapState[] MapState
        {
            get
            {
                return this.mapStateField;
            }
            set
            {
                this.mapStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Layer", typeof(LayersLayer), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LayersLayer[][] Layers
        {
            get
            {
                return this.layersField;
            }
            set
            {
                this.layersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OcxVersion
        {
            get
            {
                return this.ocxVersionField;
            }
            set
            {
                this.ocxVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileVersion
        {
            get
            {
                return this.fileVersionField;
            }
            set
            {
                this.fileVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISMapWinGISMapState
    {

        private string sendMouseMoveField;

        private string sendMouseDownField;

        private string sendMouseUpField;

        private string sendSelectBoxFinalField;

        private string trapRightMouseDownField;

        private string extentsLeftField;

        private string extentsRightField;

        private string extentsBottomField;

        private string extentsTopField;

        private string extentsPadField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SendMouseMove
        {
            get
            {
                return this.sendMouseMoveField;
            }
            set
            {
                this.sendMouseMoveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SendMouseDown
        {
            get
            {
                return this.sendMouseDownField;
            }
            set
            {
                this.sendMouseDownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SendMouseUp
        {
            get
            {
                return this.sendMouseUpField;
            }
            set
            {
                this.sendMouseUpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SendSelectBoxFinal
        {
            get
            {
                return this.sendSelectBoxFinalField;
            }
            set
            {
                this.sendSelectBoxFinalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TrapRightMouseDown
        {
            get
            {
                return this.trapRightMouseDownField;
            }
            set
            {
                this.trapRightMouseDownField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtentsLeft
        {
            get
            {
                return this.extentsLeftField;
            }
            set
            {
                this.extentsLeftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtentsRight
        {
            get
            {
                return this.extentsRightField;
            }
            set
            {
                this.extentsRightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtentsBottom
        {
            get
            {
                return this.extentsBottomField;
            }
            set
            {
                this.extentsBottomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtentsTop
        {
            get
            {
                return this.extentsTopField;
            }
            set
            {
                this.extentsTopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtentsPad
        {
            get
            {
                return this.extentsPadField;
            }
            set
            {
                this.extentsPadField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISVastGIS1
    {

        private string bookmarksField;

        private Plugin[][] pluginsField;

        private VastGISVastGIS1ApplicationPlugins[] applicationPluginsField;

        private VastGISVastGIS1PreviewMap[] previewMapField;

        private VastGISVastGIS1GroupsGroup[][] groupsField;

        private LayersLayer[][] layersField;

        private VastGISVastGIS1VastProjectInfo[] vastProjectInfoField;

        private string configurationPathField;

        private string projectProjectionField;

        private string mapUnitsField;

        private string statusBarAlternateCoordsNumDecimalsField;

        private string statusBarCoordsNumDecimalsField;

        private string statusBarAlternateCoordsUseCommasField;

        private string statusBarCoordsUseCommasField;

        private string showFloatingScaleBarField;

        private string floatingScaleBarPositionField;

        private string floatingScaleBarUnitField;

        private string floatingScaleBarForecolorField;

        private string floatingScaleBarBackcolorField;

        private string mapResizeBehaviorField;

        private string showStatusBarCoords_ProjectedField;

        private string showStatusBarCoords_AlternateField;

        private string saveShapeSettingsField;

        private string viewBackColor_UseDefaultField;

        private string viewBackColorField;

        private string projectProjectionWKTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bookmarks
        {
            get
            {
                return this.bookmarksField;
            }
            set
            {
                this.bookmarksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Plugin", typeof(Plugin), IsNullable = false)]
        public Plugin[][] Plugins
        {
            get
            {
                return this.pluginsField;
            }
            set
            {
                this.pluginsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationPlugins", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VastGISVastGIS1ApplicationPlugins[] ApplicationPlugins
        {
            get
            {
                return this.applicationPluginsField;
            }
            set
            {
                this.applicationPluginsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PreviewMap", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VastGISVastGIS1PreviewMap[] PreviewMap
        {
            get
            {
                return this.previewMapField;
            }
            set
            {
                this.previewMapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Group", typeof(VastGISVastGIS1GroupsGroup), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public VastGISVastGIS1GroupsGroup[][] Groups
        {
            get
            {
                return this.groupsField;
            }
            set
            {
                this.groupsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Layer", typeof(LayersLayer), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LayersLayer[][] Layers
        {
            get
            {
                return this.layersField;
            }
            set
            {
                this.layersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VastProjectInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VastGISVastGIS1VastProjectInfo[] VastProjectInfo
        {
            get
            {
                return this.vastProjectInfoField;
            }
            set
            {
                this.vastProjectInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConfigurationPath
        {
            get
            {
                return this.configurationPathField;
            }
            set
            {
                this.configurationPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProjectProjection
        {
            get
            {
                return this.projectProjectionField;
            }
            set
            {
                this.projectProjectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MapUnits
        {
            get
            {
                return this.mapUnitsField;
            }
            set
            {
                this.mapUnitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusBarAlternateCoordsNumDecimals
        {
            get
            {
                return this.statusBarAlternateCoordsNumDecimalsField;
            }
            set
            {
                this.statusBarAlternateCoordsNumDecimalsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusBarCoordsNumDecimals
        {
            get
            {
                return this.statusBarCoordsNumDecimalsField;
            }
            set
            {
                this.statusBarCoordsNumDecimalsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusBarAlternateCoordsUseCommas
        {
            get
            {
                return this.statusBarAlternateCoordsUseCommasField;
            }
            set
            {
                this.statusBarAlternateCoordsUseCommasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusBarCoordsUseCommas
        {
            get
            {
                return this.statusBarCoordsUseCommasField;
            }
            set
            {
                this.statusBarCoordsUseCommasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShowFloatingScaleBar
        {
            get
            {
                return this.showFloatingScaleBarField;
            }
            set
            {
                this.showFloatingScaleBarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FloatingScaleBarPosition
        {
            get
            {
                return this.floatingScaleBarPositionField;
            }
            set
            {
                this.floatingScaleBarPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FloatingScaleBarUnit
        {
            get
            {
                return this.floatingScaleBarUnitField;
            }
            set
            {
                this.floatingScaleBarUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FloatingScaleBarForecolor
        {
            get
            {
                return this.floatingScaleBarForecolorField;
            }
            set
            {
                this.floatingScaleBarForecolorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FloatingScaleBarBackcolor
        {
            get
            {
                return this.floatingScaleBarBackcolorField;
            }
            set
            {
                this.floatingScaleBarBackcolorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MapResizeBehavior
        {
            get
            {
                return this.mapResizeBehaviorField;
            }
            set
            {
                this.mapResizeBehaviorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShowStatusBarCoords_Projected
        {
            get
            {
                return this.showStatusBarCoords_ProjectedField;
            }
            set
            {
                this.showStatusBarCoords_ProjectedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShowStatusBarCoords_Alternate
        {
            get
            {
                return this.showStatusBarCoords_AlternateField;
            }
            set
            {
                this.showStatusBarCoords_AlternateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SaveShapeSettings
        {
            get
            {
                return this.saveShapeSettingsField;
            }
            set
            {
                this.saveShapeSettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ViewBackColor_UseDefault
        {
            get
            {
                return this.viewBackColor_UseDefaultField;
            }
            set
            {
                this.viewBackColor_UseDefaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ViewBackColor
        {
            get
            {
                return this.viewBackColorField;
            }
            set
            {
                this.viewBackColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProjectProjectionWKT
        {
            get
            {
                return this.projectProjectionWKTField;
            }
            set
            {
                this.projectProjectionWKTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISVastGIS1ApplicationPlugins
    {

        private Plugin[] pluginField;

        private string pluginDirField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Plugin")]
        public Plugin[] Plugin
        {
            get
            {
                return this.pluginField;
            }
            set
            {
                this.pluginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PluginDir
        {
            get
            {
                return this.pluginDirField;
            }
            set
            {
                this.pluginDirField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISVastGIS1PreviewMap
    {

        private Image[] imageField;

        private string dxField;

        private string dyField;

        private string xllcenterField;

        private string yllcenterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image")]
        public Image[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dx
        {
            get
            {
                return this.dxField;
            }
            set
            {
                this.dxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dy
        {
            get
            {
                return this.dyField;
            }
            set
            {
                this.dyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xllcenter
        {
            get
            {
                return this.xllcenterField;
            }
            set
            {
                this.xllcenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yllcenter
        {
            get
            {
                return this.yllcenterField;
            }
            set
            {
                this.yllcenterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISVastGIS1GroupsGroup
    {

        private Image[] imageField;

        private string nameField;

        private string expandedField;

        private string positionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image")]
        public Image[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expanded
        {
            get
            {
                return this.expandedField;
            }
            set
            {
                this.expandedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VastGISVastGIS1VastProjectInfo
    {

        private string projectNameField;

        private string databaseNameField;

        private string attachmentPathField;

        private string mediaPathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProjectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DatabaseName
        {
            get
            {
                return this.databaseNameField;
            }
            set
            {
                this.databaseNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttachmentPath
        {
            get
            {
                return this.attachmentPathField;
            }
            set
            {
                this.attachmentPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MediaPath
        {
            get
            {
                return this.mediaPathField;
            }
            set
            {
                this.mediaPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(Image))]
        [System.Xml.Serialization.XmlElementAttribute("LabelsClass", typeof(LabelsClass))]
        [System.Xml.Serialization.XmlElementAttribute("Layers", typeof(Layers))]
        [System.Xml.Serialization.XmlElementAttribute("Plugin", typeof(Plugin))]
        [System.Xml.Serialization.XmlElementAttribute("VastGIS", typeof(VastGIS))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
