namespace OSGeo.OGR
{
    using System;

    public enum wkbGeometryType
    {
        wkbCircularString = 8,
        wkbCircularStringM = 0x7d8,
        wkbCircularStringZ = 0x3f0,
        wkbCircularStringZM = 0xbc0,
        wkbCompoundCurve = 9,
        wkbCompoundCurveM = 0x7d9,
        wkbCompoundCurveZ = 0x3f1,
        wkbCompoundCurveZM = 0xbc1,
        wkbCurve = 13,
        wkbCurveM = 0x7dd,
        wkbCurvePolygon = 10,
        wkbCurvePolygonM = 0x7da,
        wkbCurvePolygonZ = 0x3f2,
        wkbCurvePolygonZM = 0xbc2,
        wkbCurveZ = 0x3f5,
        wkbCurveZM = 0xbc5,
        wkbGeometryCollection = 7,
        wkbGeometryCollection25D = -2147483641,
        wkbGeometryCollectionM = 0x7d7,
        wkbGeometryCollectionZM = 0xbbf,
        wkbLinearRing = 0x65,
        wkbLineString = 2,
        wkbLineString25D = -2147483646,
        wkbLineStringM = 0x7d2,
        wkbLineStringZM = 0xbba,
        wkbMultiCurve = 11,
        wkbMultiCurveM = 0x7db,
        wkbMultiCurveZ = 0x3f3,
        wkbMultiCurveZM = 0xbc3,
        wkbMultiLineString = 5,
        wkbMultiLineString25D = -2147483643,
        wkbMultiLineStringM = 0x7d5,
        wkbMultiLineStringZM = 0xbbd,
        wkbMultiPoint = 4,
        wkbMultiPoint25D = -2147483644,
        wkbMultiPointM = 0x7d4,
        wkbMultiPointZM = 0xbbc,
        wkbMultiPolygon = 6,
        wkbMultiPolygon25D = -2147483642,
        wkbMultiPolygonM = 0x7d6,
        wkbMultiPolygonZM = 0xbbe,
        wkbMultiSurface = 12,
        wkbMultiSurfaceM = 0x7dc,
        wkbMultiSurfaceZ = 0x3f4,
        wkbMultiSurfaceZM = 0xbc4,
        wkbNone = 100,
        wkbPoint = 1,
        wkbPoint25D = -2147483647,
        wkbPointM = 0x7d1,
        wkbPointZM = 0xbb9,
        wkbPolygon = 3,
        wkbPolygon25D = -2147483645,
        wkbPolygonM = 0x7d3,
        wkbPolygonZM = 0xbbb,
        wkbPolyhedralSurface = 15,
        wkbPolyhedralSurfaceM = 0x7df,
        wkbPolyhedralSurfaceZ = 0x3f7,
        wkbPolyhedralSurfaceZM = 0xbc7,
        wkbSurface = 14,
        wkbSurfaceM = 0x7de,
        wkbSurfaceZ = 0x3f6,
        wkbSurfaceZM = 0xbc6,
        wkbTIN = 0x10,
        wkbTINM = 0x7e0,
        wkbTINZ = 0x3f8,
        wkbTINZM = 0xbc8,
        wkbTriangle = 0x11,
        wkbTriangleM = 0x7e1,
        wkbTriangleZ = 0x3f9,
        wkbTriangleZM = 0xbc9,
        wkbUnknown = 0
    }
}

